name: Auto-Deployment
on:
  push:
    branches:
      - main
jobs:
  auto-deploy:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: "${{ secrets.NPM_TOKEN }}"

    steps:
      - name: Checkout V4
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install dependencies, test and build
      - name: Setting Up Node JS
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Installing node dependencies
        run: npm i

      - name: Testing storage, encryption and decryption
        run: npm run test

      - name: Building files TS -> JS
        run: npm run build

      - name: Module export checks
        run: npm run check-exports

        # Publish to npm
      - name: Publishing package
        run: npm publish
